# Generated by Django 4.2.6 on 2023-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_subespecialidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subespecialidad',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
